### PR TITLE
Rewrite the code in more readable format 

### PR DESCRIPTION
**Pull request by AlaaAbdelkareem**
simply make some indentations and comments

### CODE REVIEW

**Comment by benoror** [comment]
> simply make some indentations and comments

what else an be done?

**Comment by AlaaAbdelkareem** [comment]
i will write my steps to do that in file and send it , any thing else?

**Comment by AlaaAbdelkareem** [comment]
then i will restart research how to make Semantic Commits

**Comment by benoror** [comment]
> i will write my steps to do that in file and send it , any thing else?

the more the better :)

**Comment by AlaaAbdelkareem** [comment]
Ok , i will do my best :)

**Comment by AlaaAbdelkareem** [comment]
Greeting,

hope my mail finds you well, I did my best to finish task and match the
deadline.
hope it will match your requirements .
please send me feedback.

https://github.com/AlaaAbdelkareem/ecs-tests

Best Regard,
Alaa Abdelkareem

**Comment by benoror** [comment]
In review

**Pull request closed without merging**
